name: Release

on:
  push:
    branches-ignore:
      - assets**
      - dist**
      - gh-pages
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
      - name: Build
        run: mise run dist
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: dist-${{ matrix.arch }}-${{ matrix.os }}
          path: dist
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        os:
          - darwin
          - freebsd
          - linux
          - windows

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build
    if: startsWith(github.ref, 'ref/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Download Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true
      - name: Release
        uses: liblaf/actions-ts/release@5c8004180418b0da5cbd10a97b4d34dec0ac66dc # main
        with:
          files: dist/*
          tag: ${{ github.ref_name }}
