name: Release

on:
  push:
    branches-ignore:
      - assets**
      - dist**
      - gh-pages
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install mise
        uses: jdx/mise-action@v3
      - name: Setup Go
        uses: actions/setup-go@v6
      - name: Build
        run: mise run dist
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.arch }}-${{ matrix.os }}
          path: dist
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        os:
          - darwin
          - freebsd
          - linux
          - windows

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build
    if: startsWith(github.ref, 'ref/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true
      - name: Release
        uses: liblaf/actions-ts/release@main
        with:
          files: dist/*
          tag: ${{ github.ref_name }}
