name: Release

on:
  push:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Setup Just
        uses: extractions/setup-just@v3
      - name: Build
        run: just dist
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.arch }}-${{ matrix.os }}
          path: ./bin/
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        os:
          - darwin
          - freebsd
          - linux
          - windows

  pre-release:
    name: Pre-Release
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-pre-release
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./bin/
          pattern: bin-*
          merge-multiple: true
      - name: Release
        uses: liblaf/actions/release@main
        with:
          clobber: true
          files: ./bin/*
          prerelease: true
          tag: dev

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build
    if: github.event_name == 'release' || startsWith(github.ref, 'ref/tags/v')
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-release
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./bin/
          pattern: bin-*
          merge-multiple: true
      - name: Release
        uses: liblaf/actions/release@main
        with:
          files: ./bin/*
          tag: ${{ github.event.release.tag_name || github.ref_name }}
